"""Move the original business's identity out of code and into Settings.

Before this CRM was white-labelled, the business's name was not stored anywhere.
It lived as a fallback argument scattered through the code —
`BusinessSetting.get('business_name', 'Dazzle & Shine Maids')` — so the name
appeared everywhere while the setting itself stayed empty.

Removing those fallbacks was necessary (they are exactly what stopped a second
company using the CRM), but it meant the original business suddenly had no name
at all and fell through to a placeholder.

This restores it: the name, the palette, the separate commercial brand and the
Google review link all become real rows in Settings, which is where they should
have lived from the start.

Identifying the original instance is done from its data, not from its name — the
name is precisely what went missing. Any quote ever raised on this CRM carries a
brand key of 'lm' or 'dazzle', and those keys were only ever generated by the
original deployment. A CRM stood up for anybody else has no such rows and is
never touched by this.
"""

LEGACY_NAME = 'Dazzle & Shine Maids'

LEGACY_SETTINGS = {
    # The residential brand — the business's own name and gold palette.
    'brand_tagline': 'Professional Cleaning Proposal',
    'brand_dark': '#1f1333',
    'brand_accent': '#d3a84f',
    'brand_accent_text': '#1f1333',
    'brand_domain_verified': '1',
    # The commercial side, which sells under a separate name.
    'commercial_name': 'L & M Commercial Cleaners',
    'commercial_tagline': 'Commercial Cleaning Proposal',
    'commercial_from_email': 'admin@commercialcleanersorlando.com',
    'commercial_reply_to': 'admin@commercialcleanersorlando.com',
    'commercial_website': 'www.commercialcleanersorlando.com',
    'commercial_dark': '#12324a',
    'commercial_accent': '#2a89c4',
    'commercial_accent_text': '#ffffff',
    'commercial_domain_verified': '',
    # The review link used to be a code default. It is now a setting with no
    # default at all, because pointing a happy customer at the wrong company's
    # review page is worse than showing no button.
    'google_review_link': 'https://g.page/r/CZLGfXgsWHtVEBM/review',
}


def _is_original_instance():
    """True only for the deployment this CRM was originally built for."""
    from models import BusinessSetting
    if (BusinessSetting.get('business_name') or '').strip() == LEGACY_NAME:
        return True
    try:
        from models import CommercialQuote
        return CommercialQuote.query.filter(
            CommercialQuote.brand.in_(('lm', 'dazzle'))).count() > 0
    except Exception:
        return False


def restore_if_original():
    """Write the original business's details into Settings, once.

    Safe to call repeatedly and safe to call on any deployment: it does nothing
    unless the data says this is the original instance, and it never overwrites
    a value somebody has already set."""
    from models import BusinessSetting
    from extensions import db

    if BusinessSetting.get('brand_settings_migrated'):
        return False
    if not _is_original_instance():
        return False

    if not (BusinessSetting.get('business_name') or '').strip():
        BusinessSetting.set('business_name', LEGACY_NAME)
    for key, value in LEGACY_SETTINGS.items():
        if not BusinessSetting.get(key):
            BusinessSetting.set(key, value)
    BusinessSetting.set('brand_settings_migrated', '1')
    db.session.commit()
    return True
