"""The schema as it stands today.

Not a migration anybody runs against an existing database. It is the starting
line: every instance already carrying these tables is stamped at this revision
without executing it, and only genuinely new instances create them from here.
See migrate.py for how that decision is made.
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('checklist_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('portal_token', sa.String(length=64), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(length=100), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('autopay', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_portal_token'), 'client', ['portal_token'], unique=False)
    op.create_table('commercial_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('square_footage', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('frequency', sa.String(length=30), nullable=True),
    sa.Column('billing_type', sa.String(length=20), nullable=True),
    sa.Column('billing_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('first_paid_at', sa.DateTime(), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commercial_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('property_address', sa.String(length=200), nullable=True),
    sa.Column('units', sa.String(length=20), nullable=True),
    sa.Column('sqft', sa.String(length=20), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('contract_term', sa.String(length=50), nullable=True),
    sa.Column('price_per_visit', sa.Float(), nullable=True),
    sa.Column('monthly_price', sa.Float(), nullable=True),
    sa.Column('scope_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=10), nullable=True),
    sa.Column('drip_step', sa.Integer(), nullable=True),
    sa.Column('last_drip_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('commission_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent', 'year', 'month', name='uq_commission_agent_month')
    )
    op.create_index(op.f('ix_commission_payment_agent'), 'commission_payment', ['agent'], unique=False)
    op.create_index(op.f('ix_commission_payment_paid_at'), 'commission_payment', ['paid_at'], unique=False)
    op.create_table('content_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractor_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('years_experience', sa.String(length=20), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('has_transportation', sa.Boolean(), nullable=True),
    sa.Column('has_supplies', sa.Boolean(), nullable=True),
    sa.Column('has_references', sa.Boolean(), nullable=True),
    sa.Column('background_check_consent', sa.Boolean(), nullable=True),
    sa.Column('agrees_to_ic_terms', sa.Boolean(), nullable=True),
    sa.Column('why_interested', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('phone_interview_completed', sa.Boolean(), nullable=True),
    sa.Column('phone_interview_at', sa.DateTime(), nullable=True),
    sa.Column('phone_interview_notes', sa.Text(), nullable=True),
    sa.Column('background_check_status', sa.String(length=20), nullable=True),
    sa.Column('background_check_notes', sa.Text(), nullable=True),
    sa.Column('background_check_at', sa.DateTime(), nullable=True),
    sa.Column('bgcheck_existing_link', sa.String(length=500), nullable=True),
    sa.Column('bgcheck_request_sent_at', sa.DateTime(), nullable=True),
    sa.Column('bgcheck_results_received', sa.Boolean(), nullable=True),
    sa.Column('bgcheck_upload_token', sa.String(length=64), nullable=True),
    sa.Column('bgcheck_uploaded_url', sa.String(length=500), nullable=True),
    sa.Column('bgcheck_uploaded_link', sa.String(length=500), nullable=True),
    sa.Column('bgcheck_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('ref1_name', sa.String(length=100), nullable=True),
    sa.Column('ref1_phone', sa.String(length=20), nullable=True),
    sa.Column('ref1_notes', sa.Text(), nullable=True),
    sa.Column('ref1_called', sa.Boolean(), nullable=True),
    sa.Column('ref2_name', sa.String(length=100), nullable=True),
    sa.Column('ref2_phone', sa.String(length=20), nullable=True),
    sa.Column('ref2_notes', sa.Text(), nullable=True),
    sa.Column('ref2_called', sa.Boolean(), nullable=True),
    sa.Column('interview_invite_sent_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_sent_at', sa.DateTime(), nullable=True),
    sa.Column('interview_token', sa.String(length=64), nullable=True),
    sa.Column('interview_status', sa.String(length=20), nullable=True),
    sa.Column('interview_sent_at', sa.DateTime(), nullable=True),
    sa.Column('interview_completed_at', sa.DateTime(), nullable=True),
    sa.Column('interview_nudge_count', sa.Integer(), nullable=True),
    sa.Column('interview_last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('offer_sent_at', sa.DateTime(), nullable=True),
    sa.Column('offer_sent_count', sa.Integer(), nullable=True),
    sa.Column('offer_token', sa.String(length=64), nullable=True),
    sa.Column('offer_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_token'),
    sa.UniqueConstraint('offer_token')
    )
    op.create_table('cron_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=40), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('items', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_run_job'), 'cron_run', ['job'], unique=False)
    op.create_index(op.f('ix_cron_run_ran_at'), 'cron_run', ['ran_at'], unique=False)
    op.create_table('discount_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('email_opt_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_opt_out_email'), 'email_opt_out', ['email'], unique=True)
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger')
    )
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=400), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=120), nullable=True),
    sa.Column('who', sa.String(length=60), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('alerted_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_log_fingerprint'), 'error_log', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_error_log_last_seen'), 'error_log', ['last_seen'], unique=False)
    op.create_index(op.f('ix_error_log_resolved'), 'error_log', ['resolved'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('bedrooms', sa.String(length=10), nullable=True),
    sa.Column('bathrooms', sa.String(length=10), nullable=True),
    sa.Column('extras', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.Column('drip_step', sa.Integer(), nullable=True),
    sa.Column('last_drip_at', sa.DateTime(), nullable=True),
    sa.Column('quote_token', sa.String(length=64), nullable=True),
    sa.Column('quote_sent_at', sa.DateTime(), nullable=True),
    sa.Column('quote_checklist', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_brand'), 'lead', ['brand'], unique=False)
    op.create_index(op.f('ix_lead_quote_token'), 'lead', ['quote_token'], unique=False)
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempt_created_at'), 'login_attempt', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempt_ip'), 'login_attempt', ['ip'], unique=False)
    op.create_index(op.f('ix_login_attempt_ok'), 'login_attempt', ['ok'], unique=False)
    op.create_table('lsa_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('job_type', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('lead_type', sa.String(length=40), nullable=True),
    sa.Column('charge_status', sa.String(length=40), nullable=True),
    sa.Column('track', sa.String(length=20), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('booked_checked_at', sa.DateTime(), nullable=True),
    sa.Column('crm_lead_id', sa.Integer(), nullable=True),
    sa.Column('seq_step', sa.Integer(), nullable=True),
    sa.Column('seq_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_seq_at', sa.DateTime(), nullable=True),
    sa.Column('seq_stopped', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lsa_lead_lead_id'), 'lsa_lead', ['lead_id'], unique=True)
    op.create_index(op.f('ix_lsa_lead_phone'), 'lsa_lead', ['phone'], unique=False)
    op.create_index(op.f('ix_lsa_lead_received_at'), 'lsa_lead', ['received_at'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_translated', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('twilio_sid', sa.String(length=64), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_phone'), 'message', ['phone'], unique=False)
    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('to_address', sa.String(length=200), nullable=True),
    sa.Column('to_name', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('detail', sa.String(length=400), nullable=True),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_log_created_at'), 'outbound_log', ['created_at'], unique=False)
    op.create_table('pricing_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('processing_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_processing_fee_month')
    )
    op.create_table('prospect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('place_id', sa.String(length=220), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('next_action', sa.String(length=120), nullable=True),
    sa.Column('next_action_date', sa.String(length=10), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('renewal_note', sa.String(length=120), nullable=True),
    sa.Column('last_emailed_at', sa.DateTime(), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_brand'), 'prospect', ['brand'], unique=False)
    op.create_index(op.f('ix_prospect_created_at'), 'prospect', ['created_at'], unique=False)
    op.create_index(op.f('ix_prospect_next_action_date'), 'prospect', ['next_action_date'], unique=False)
    op.create_index(op.f('ix_prospect_place_id'), 'prospect', ['place_id'], unique=False)
    op.create_index(op.f('ix_prospect_stage'), 'prospect', ['stage'], unique=False)
    op.create_table('recurring_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_posted', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_opt_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_opt_out_phone'), 'sms_opt_out', ['phone'], unique=True)
    op.create_table('sop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('bedrooms', sa.String(length=10), nullable=True),
    sa.Column('bathrooms', sa.String(length=10), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('extras', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('preferred_date', sa.String(length=50), nullable=True),
    sa.Column('preferred_time', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('stripe_payment_intent', sa.String(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(length=100), nullable=True),
    sa.Column('deposit_paid', sa.Boolean(), nullable=True),
    sa.Column('deposit_paid_at', sa.DateTime(), nullable=True),
    sa.Column('deposit_notified_at', sa.DateTime(), nullable=True),
    sa.Column('deposit_token', sa.String(length=64), nullable=True),
    sa.Column('tip_amount', sa.Float(), nullable=True),
    sa.Column('tip_payment_intent', sa.String(length=100), nullable=True),
    sa.Column('balance_due', sa.Float(), nullable=True),
    sa.Column('balance_collected', sa.Boolean(), nullable=True),
    sa.Column('pay_token', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_method', sa.String(length=20), nullable=True),
    sa.Column('invoice_sent_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_number', sa.String(length=20), nullable=True),
    sa.Column('invoice_issued_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_due_date', sa.String(length=10), nullable=True),
    sa.Column('lead_fee', sa.Float(), nullable=True),
    sa.Column('discount_code', sa.String(length=50), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('owner_hours', sa.Float(), nullable=True),
    sa.Column('labor_rate_applied', sa.Float(), nullable=True),
    sa.Column('below_floor_reason', sa.String(length=200), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('cleaner_paid_at', sa.DateTime(), nullable=True),
    sa.Column('cleaner_payment_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('recurring_group', sa.String(length=32), nullable=True),
    sa.Column('recurring_active', sa.Boolean(), nullable=True),
    sa.Column('monthly_mode', sa.String(length=10), nullable=True),
    sa.Column('confirm_token', sa.String(length=64), nullable=True),
    sa.Column('confirm_sent_at', sa.DateTime(), nullable=True),
    sa.Column('confirm_note', sa.Text(), nullable=True),
    sa.Column('confirm_response', sa.String(length=10), nullable=True),
    sa.Column('confirm_alt', sa.Text(), nullable=True),
    sa.Column('onsite_people', sa.Text(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted_text', sa.Text(), nullable=True),
    sa.Column('terms_accepted_ip', sa.String(length=64), nullable=True),
    sa.Column('confirm_responded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('assigned_cleaner', sa.String(length=100), nullable=True),
    sa.Column('crew_size', sa.Integer(), nullable=True),
    sa.Column('crew_pay_each', sa.Float(), nullable=True),
    sa.Column('cleaner_notified_at', sa.DateTime(), nullable=True),
    sa.Column('cleaner_response', sa.String(length=20), nullable=True),
    sa.Column('open_for_claim', sa.Boolean(), nullable=True),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('broadcast_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('morning_note_at', sa.DateTime(), nullable=True),
    sa.Column('review_nudge_at', sa.DateTime(), nullable=True),
    sa.Column('skip_review', sa.Boolean(), nullable=True),
    sa.Column('upsell_sent_at', sa.DateTime(), nullable=True),
    sa.Column('upsell_nudge_at', sa.DateTime(), nullable=True),
    sa.Column('winback_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_confirm_token'), 'booking', ['confirm_token'], unique=False)
    op.create_index(op.f('ix_booking_recurring_group'), 'booking', ['recurring_group'], unique=False)
    op.create_table('interview_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question_en', sa.Text(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=200), nullable=True),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_lang', sa.String(length=10), nullable=True),
    sa.Column('transcript_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['contractor_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('pay_type', sa.String(length=20), nullable=True),
    sa.Column('pay_rate', sa.Float(), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('has_transportation', sa.Boolean(), nullable=True),
    sa.Column('has_supplies', sa.Boolean(), nullable=True),
    sa.Column('worker_model', sa.String(length=20), nullable=True),
    sa.Column('onboarding_steps', sa.Text(), nullable=True),
    sa.Column('agreement_token', sa.String(length=64), nullable=True),
    sa.Column('agreement_signature', sa.String(length=100), nullable=True),
    sa.Column('agreement_signed_at', sa.DateTime(), nullable=True),
    sa.Column('shirt_size', sa.String(length=10), nullable=True),
    sa.Column('payment_pref', sa.String(length=50), nullable=True),
    sa.Column('payment_notes', sa.String(length=200), nullable=True),
    sa.Column('welcome_forms_at', sa.DateTime(), nullable=True),
    sa.Column('orientation_token', sa.String(length=64), nullable=True),
    sa.Column('orientation_completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_payouts_enabled', sa.Boolean(), nullable=True),
    sa.Column('stripe_details_submitted', sa.Boolean(), nullable=True),
    sa.Column('stripe_disabled_reason', sa.String(length=120), nullable=True),
    sa.Column('pay_schedule', sa.String(length=10), nullable=True),
    sa.Column('insurance_reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('roster_start_date', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('onboarding_reminder_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_reminder_count', sa.Integer(), nullable=True),
    sa.Column('schedule_reminder_date', sa.String(length=20), nullable=True),
    sa.Column('w9_url', sa.String(length=500), nullable=True),
    sa.Column('w9_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('w9_requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['contractor_application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_token'),
    sa.UniqueConstraint('orientation_token')
    )
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'day', name='uq_availability_staff_day')
    )
    op.create_index(op.f('ix_availability_day'), 'availability', ['day'], unique=False)
    op.create_index(op.f('ix_availability_staff_id'), 'availability', ['staff_id'], unique=False)
    op.create_table('booking_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('pay_amount', sa.Float(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'staff_id', name='uq_crew_booking_staff')
    )
    op.create_index(op.f('ix_booking_crew_booking_id'), 'booking_crew', ['booking_id'], unique=False)
    op.create_table('booking_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('contractor_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['contractor_application.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'kind', name='uq_doc_app_kind'),
    sa.UniqueConstraint('staff_id', 'kind', name='uq_doc_staff_kind')
    )
    op.create_index(op.f('ix_contractor_document_application_id'), 'contractor_document', ['application_id'], unique=False)
    op.create_index(op.f('ix_contractor_document_staff_id'), 'contractor_document', ['staff_id'], unique=False)
    op.create_table('contractor_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tip_amount', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_transfer_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('receipt_url', sa.String(length=400), nullable=True),
    sa.Column('miles', sa.Float(), nullable=True),
    sa.Column('rate_per_mile', sa.Float(), nullable=True),
    sa.Column('recurring_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring_expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_booking_id'), 'expense', ['booking_id'], unique=False)
    op.create_index(op.f('ix_expense_category'), 'expense', ['category'], unique=False)
    op.create_index(op.f('ix_expense_date'), 'expense', ['date'], unique=False)
    op.create_table('job_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('completed_items', sa.Text(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('before_photos', sa.Text(), nullable=True),
    sa.Column('after_photos', sa.Text(), nullable=True),
    sa.Column('photos_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('on_the_way_at', sa.DateTime(), nullable=True),
    sa.Column('clock_in_at', sa.DateTime(), nullable=True),
    sa.Column('clock_out_at', sa.DateTime(), nullable=True),
    sa.Column('client_signature', sa.Text(), nullable=True),
    sa.Column('client_signed_at', sa.DateTime(), nullable=True),
    sa.Column('client_rating', sa.Integer(), nullable=True),
    sa.Column('client_review', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_checklist')
    op.drop_index(op.f('ix_expense_date'), table_name='expense')
    op.drop_index(op.f('ix_expense_category'), table_name='expense')
    op.drop_index(op.f('ix_expense_booking_id'), table_name='expense')
    op.drop_table('expense')
    op.drop_table('contractor_payment')
    op.drop_index(op.f('ix_contractor_document_staff_id'), table_name='contractor_document')
    op.drop_index(op.f('ix_contractor_document_application_id'), table_name='contractor_document')
    op.drop_table('contractor_document')
    op.drop_table('booking_rating')
    op.drop_index(op.f('ix_booking_crew_booking_id'), table_name='booking_crew')
    op.drop_table('booking_crew')
    op.drop_index(op.f('ix_availability_staff_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_day'), table_name='availability')
    op.drop_table('availability')
    op.drop_table('staff')
    op.drop_table('interview_response')
    op.drop_index(op.f('ix_booking_recurring_group'), table_name='booking')
    op.drop_index(op.f('ix_booking_confirm_token'), table_name='booking')
    op.drop_table('booking')
    op.drop_table('user')
    op.drop_table('sop')
    op.drop_index(op.f('ix_sms_opt_out_phone'), table_name='sms_opt_out')
    op.drop_table('sms_opt_out')
    op.drop_table('script')
    op.drop_table('recurring_expense')
    op.drop_index(op.f('ix_prospect_stage'), table_name='prospect')
    op.drop_index(op.f('ix_prospect_place_id'), table_name='prospect')
    op.drop_index(op.f('ix_prospect_next_action_date'), table_name='prospect')
    op.drop_index(op.f('ix_prospect_created_at'), table_name='prospect')
    op.drop_index(op.f('ix_prospect_brand'), table_name='prospect')
    op.drop_table('prospect')
    op.drop_table('processing_fee')
    op.drop_table('pricing_setting')
    op.drop_index(op.f('ix_outbound_log_created_at'), table_name='outbound_log')
    op.drop_table('outbound_log')
    op.drop_table('message_template')
    op.drop_index(op.f('ix_message_phone'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_lsa_lead_received_at'), table_name='lsa_lead')
    op.drop_index(op.f('ix_lsa_lead_phone'), table_name='lsa_lead')
    op.drop_index(op.f('ix_lsa_lead_lead_id'), table_name='lsa_lead')
    op.drop_table('lsa_lead')
    op.drop_index(op.f('ix_login_attempt_ok'), table_name='login_attempt')
    op.drop_index(op.f('ix_login_attempt_ip'), table_name='login_attempt')
    op.drop_index(op.f('ix_login_attempt_created_at'), table_name='login_attempt')
    op.drop_table('login_attempt')
    op.drop_index(op.f('ix_lead_quote_token'), table_name='lead')
    op.drop_index(op.f('ix_lead_brand'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_error_log_resolved'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_last_seen'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_fingerprint'), table_name='error_log')
    op.drop_table('error_log')
    op.drop_table('email_template')
    op.drop_index(op.f('ix_email_opt_out_email'), table_name='email_opt_out')
    op.drop_table('email_opt_out')
    op.drop_table('discount_code')
    op.drop_index(op.f('ix_cron_run_ran_at'), table_name='cron_run')
    op.drop_index(op.f('ix_cron_run_job'), table_name='cron_run')
    op.drop_table('cron_run')
    op.drop_table('contractor_application')
    op.drop_table('content_post')
    op.drop_index(op.f('ix_commission_payment_paid_at'), table_name='commission_payment')
    op.drop_index(op.f('ix_commission_payment_agent'), table_name='commission_payment')
    op.drop_table('commission_payment')
    op.drop_table('commercial_quote')
    op.drop_table('commercial_account')
    op.drop_index(op.f('ix_client_portal_token'), table_name='client')
    op.drop_table('client')
    op.drop_table('checklist_template')
    op.drop_table('business_setting')
    # ### end Alembic commands ###
