"""Money columns become exact decimals.

Twenty columns move from double precision to NUMERIC(10,2). Postgres rounds
each existing value to the cent on the way across, which is what every one of
them already meant -- $1.13 has been sitting in the database as 1.12999999...
since the day it was written, and this is where it stops.

Written by hand rather than autogenerated, for two reasons.

Autogenerate could not see the change: it was run against SQLite, which has no
real NUMERIC type and reports no difference. Running it against production to
find out is not a thing to do.

And what it did produce was a DROP COLUMN. `contractor_application.
experience_years` exists in production and not in models.py -- a column from an
older release that nothing reads any more. Autogenerate saw the difference and
proposed deleting it, which would have destroyed real answers given by real
applicants, in a migration whose stated purpose was rounding. Drift gets left
alone here; removing a column is its own decision, taken deliberately, with a
backup taken first.

Reversible. The downgrade puts the type back; the cents that were rounded away
were never accurate to begin with.
"""
from alembic import op
import sqlalchemy as sa

revision = '0002_money_to_numeric'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None

# Deliberately not every Float column. Hours are hours, miles are a distance,
# and a Google star rating is not a currency -- those stay as they are.
MONEY_COLUMNS = [
    ('commercial_account', 'billing_amount'),
    ('commercial_quote', 'price_per_visit'),
    ('commercial_quote', 'monthly_price'),
    ('commission_payment', 'amount'),
    ('discount_code', 'discount_value'),
    ('lead', 'quoted_price'),
    ('processing_fee', 'amount'),
    ('recurring_expense', 'amount'),
    ('booking', 'tip_amount'),
    ('booking', 'balance_due'),
    ('booking', 'lead_fee'),
    ('booking', 'discount_amount'),
    ('booking', 'labor_rate_applied'),
    ('booking', 'crew_pay_each'),
    ('booking', 'price'),
    ('staff', 'pay_rate'),
    ('booking_crew', 'pay_amount'),
    ('contractor_payment', 'amount'),
    ('contractor_payment', 'tip_amount'),
    ('expense', 'amount'),
]


def _is_sqlite():
    """SQLite has no NUMERIC type to convert to and does not enforce column
    types anyway, so there is nothing to do and no way to do it. Local and test
    databases pass straight through; production is Postgres, where it matters."""
    return op.get_bind().dialect.name == 'sqlite'


def upgrade():
    if _is_sqlite():
        return
    for table, column in MONEY_COLUMNS:
        op.alter_column(
            table, column,
            type_=sa.Numeric(10, 2),
            existing_type=sa.Float(),
            existing_nullable=True,
            # ROUND to the cent explicitly. Without it Postgres keeps whatever
            # binary noise was in the float, and a column called NUMERIC(10,2)
            # would still be holding a value that was never a real amount.
            postgresql_using=f'ROUND({column}::numeric, 2)',
        )


def downgrade():
    if _is_sqlite():
        return
    for table, column in MONEY_COLUMNS:
        op.alter_column(
            table, column,
            type_=sa.Float(),
            existing_type=sa.Numeric(10, 2),
            existing_nullable=True,
            postgresql_using=f'{column}::double precision',
        )
